contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
baseurl = "http://sh33tal.github.io/"
canonifyurls = true
[indexes] 
       category = "categories"
       tag = "tags"
[params]
title = "My blogs"
linkedinLink = "https://uk.linkedin.com/pub/hetal-patel/0/a94/54"
facebook = "http://facebook.com" 
