contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
baseurl = "http://www.hetal-patel.com/"
canonifyurls = true
[indexes] 
       category = "categories"
       tag = "tags"

